//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopcion
    {
        public int id_Adopcion { get; set; }
        public string fecha_registro { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string tel { get; set; }
        public string r1 { get; set; }
        public string r2 { get; set; }
        public string r3 { get; set; }
        public string r4 { get; set; }
        public Nullable<double> Donacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_animal { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
