//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Adopcion = new HashSet<Adopcion>();
        }
    
        public int id_animal { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string raza { get; set; }
        public string sexo { get; set; }
        public string color { get; set; }
        public Nullable<int> edad { get; set; }
        public string tamaño { get; set; }
        public string foto { get; set; }
        public string detalles { get; set; }
        public string fecha_registro { get; set; }
        public string estado_adopcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopcion> Adopcion { get; set; }
    }
}
